ARG BASE

FROM ${BASE}

LABEL Martin Sjölund <martin.sjolund@liu.se>

RUN export DEBIAN_FRONTEND="noninteractive" \
    && apt-get install ca-certificates gnupg \
    && echo "deb https://build.openmodelica.org/apt `cat /etc/lsb-release | grep CODENAME | cut -d= -f2` nightly" > /etc/apt/sources.list.d/openmodelica.list \
    && apt-get update \
    && apt-get install -qy openmodelica libomccpp qtwayland5 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
