ARG BASE

FROM ${BASE}

LABEL Martin Sjölund <martin.sjolund@liu.se>

RUN export DEBIAN_FRONTEND="noninteractive" \
    && apt-get update \
    && apt-get install -qy openmodelica libomccpp qtwayland5 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
