ARG BASE

FROM ${BASE}

LABEL Martin Sjölund <martin.sjolund@liu.se>

RUN export DEBIAN_FRONTEND="noninteractive" \
    && apt-get update \
    && apt-get install -o Acquire::ForceIPv4=true -qy software-properties-common \
    && add-apt-repository ppa:aslatter/ppa -y \
    && apt-get install -o Acquire::ForceIPv4=true -qy openmodelica libomccpp qtwayland5 alacritty \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
