#!/usr/bin/env bash

OMVER=${OMVER:-v1.20.0}
TEMPDIR="${TEMPDIR:-$(pwd)/.OMtmp}"
WD="${WD:-$(pwd)}"
echo "using OM version $OMVER XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR / WAYLAND_DISPLAY=$WAYLAND_DISPLAY / TEMPDIR=$TEMPDIR ..."

mkdir -p "$TEMPDIR"
docker run \
	--network=host \
	-e XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
	-e WAYLAND_DISPLAY="$WAYLAND_DISPLAY" \
	-e XDG_SESSION_TYPE=wayland \
	-e QT_QPA_PLATFORM=wayland \
	-e MODELICAPATH="$HOME/.openmodelica/libraries" \
	-v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"  \
	-v "$HOME:$HOME" \
	-v "$TEMPDIR:/tmp" \
	-w "$WD" \
	-e HOME="$HOME" \
	--user="$(id -u):$(id -g)" \
	--rm -dt \
	--name=openmodelica \
	openmodelica/openmodelica:$OMVER-gui OMEdit

